# Generated by Django 2.2.1 on 2019-10-25 05:08

from django.db import migrations
import urllib.request
import json 

def populate_db (apps, shema_editor):
    Votacao = apps.get_model('api', 'Votacao')
    url = 'http://dados.movimentoacredito.org/processo-seletivo/votacoes_nominais_em_plenario.json'
    with urllib.request.urlopen(url) as json_file:
        data = json.loads(json_file.read().decode())
        print("Populate DB with JSON data")
        for element in data:    
            Votacao.objects.create(**element)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_votacao'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
