# Generated by Django 2.2.1 on 2019-10-25 05:08

from django.db import migrations
import urllib.request
import json 

def populate_db (apps, shema_editor):
    Votacao = apps.get_model('api', 'Votacao')
    url = 'https://raw.githubusercontent.com/fernand0aguilar/redesigned-invention/master/backend/api/sample.json'
    with urllib.request.urlopen(url) as json_file:
        data = json.loads(json_file.read().decode())
        print("Populate DB with JSON data")
        for element in data:
            Votacao.objects.create(**element)
    
        

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191023_1737'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
